# NOTE: This file may be out of date. Regenerate from proto/arvak.proto if streaming RPCs are needed.
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import arvak_pb2 as arvak__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in arvak_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ArvakServiceStub(object):
    """============================================================================
    Service RPCs
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitJob = channel.unary_unary(
                '/arvak.v1.ArvakService/SubmitJob',
                request_serializer=arvak__pb2.SubmitJobRequest.SerializeToString,
                response_deserializer=arvak__pb2.SubmitJobResponse.FromString,
                _registered_method=True)
        self.SubmitBatch = channel.unary_unary(
                '/arvak.v1.ArvakService/SubmitBatch',
                request_serializer=arvak__pb2.SubmitBatchRequest.SerializeToString,
                response_deserializer=arvak__pb2.SubmitBatchResponse.FromString,
                _registered_method=True)
        self.GetJobStatus = channel.unary_unary(
                '/arvak.v1.ArvakService/GetJobStatus',
                request_serializer=arvak__pb2.GetJobStatusRequest.SerializeToString,
                response_deserializer=arvak__pb2.GetJobStatusResponse.FromString,
                _registered_method=True)
        self.GetJobResult = channel.unary_unary(
                '/arvak.v1.ArvakService/GetJobResult',
                request_serializer=arvak__pb2.GetJobResultRequest.SerializeToString,
                response_deserializer=arvak__pb2.GetJobResultResponse.FromString,
                _registered_method=True)
        self.CancelJob = channel.unary_unary(
                '/arvak.v1.ArvakService/CancelJob',
                request_serializer=arvak__pb2.CancelJobRequest.SerializeToString,
                response_deserializer=arvak__pb2.CancelJobResponse.FromString,
                _registered_method=True)
        self.ListBackends = channel.unary_unary(
                '/arvak.v1.ArvakService/ListBackends',
                request_serializer=arvak__pb2.ListBackendsRequest.SerializeToString,
                response_deserializer=arvak__pb2.ListBackendsResponse.FromString,
                _registered_method=True)
        self.GetBackendInfo = channel.unary_unary(
                '/arvak.v1.ArvakService/GetBackendInfo',
                request_serializer=arvak__pb2.GetBackendInfoRequest.SerializeToString,
                response_deserializer=arvak__pb2.GetBackendInfoResponse.FromString,
                _registered_method=True)


class ArvakServiceServicer(object):
    """============================================================================
    Service RPCs
    ============================================================================

    """

    def SubmitJob(self, request, context):
        """/ Submit a single job for execution.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitBatch(self, request, context):
        """/ Submit multiple jobs as a batch.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobStatus(self, request, context):
        """/ Get the status of a job.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobResult(self, request, context):
        """/ Get the result of a completed job.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelJob(self, request, context):
        """/ Cancel a running or queued job.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBackends(self, request, context):
        """/ List all available backends.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBackendInfo(self, request, context):
        """/ Get detailed information about a specific backend.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArvakServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitJob': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitJob,
                    request_deserializer=arvak__pb2.SubmitJobRequest.FromString,
                    response_serializer=arvak__pb2.SubmitJobResponse.SerializeToString,
            ),
            'SubmitBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitBatch,
                    request_deserializer=arvak__pb2.SubmitBatchRequest.FromString,
                    response_serializer=arvak__pb2.SubmitBatchResponse.SerializeToString,
            ),
            'GetJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobStatus,
                    request_deserializer=arvak__pb2.GetJobStatusRequest.FromString,
                    response_serializer=arvak__pb2.GetJobStatusResponse.SerializeToString,
            ),
            'GetJobResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobResult,
                    request_deserializer=arvak__pb2.GetJobResultRequest.FromString,
                    response_serializer=arvak__pb2.GetJobResultResponse.SerializeToString,
            ),
            'CancelJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelJob,
                    request_deserializer=arvak__pb2.CancelJobRequest.FromString,
                    response_serializer=arvak__pb2.CancelJobResponse.SerializeToString,
            ),
            'ListBackends': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBackends,
                    request_deserializer=arvak__pb2.ListBackendsRequest.FromString,
                    response_serializer=arvak__pb2.ListBackendsResponse.SerializeToString,
            ),
            'GetBackendInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBackendInfo,
                    request_deserializer=arvak__pb2.GetBackendInfoRequest.FromString,
                    response_serializer=arvak__pb2.GetBackendInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arvak.v1.ArvakService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('arvak.v1.ArvakService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ArvakService(object):
    """============================================================================
    Service RPCs
    ============================================================================

    """

    @staticmethod
    def SubmitJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arvak.v1.ArvakService/SubmitJob',
            arvak__pb2.SubmitJobRequest.SerializeToString,
            arvak__pb2.SubmitJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arvak.v1.ArvakService/SubmitBatch',
            arvak__pb2.SubmitBatchRequest.SerializeToString,
            arvak__pb2.SubmitBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arvak.v1.ArvakService/GetJobStatus',
            arvak__pb2.GetJobStatusRequest.SerializeToString,
            arvak__pb2.GetJobStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJobResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arvak.v1.ArvakService/GetJobResult',
            arvak__pb2.GetJobResultRequest.SerializeToString,
            arvak__pb2.GetJobResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arvak.v1.ArvakService/CancelJob',
            arvak__pb2.CancelJobRequest.SerializeToString,
            arvak__pb2.CancelJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBackends(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arvak.v1.ArvakService/ListBackends',
            arvak__pb2.ListBackendsRequest.SerializeToString,
            arvak__pb2.ListBackendsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBackendInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arvak.v1.ArvakService/GetBackendInfo',
            arvak__pb2.GetBackendInfoRequest.SerializeToString,
            arvak__pb2.GetBackendInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
